package pestControl.nodes;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 * @author Pen
 */
public class Gui extends JFrame {

    private JComboBox jComboBox1;

    /**
     * Creates new form fighterGUI
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();
        jComboBox1 = new JComboBox();
        JLabel jLabel3 = new JLabel();
        JCheckBox portalCheck = new JCheckBox();
        JCheckBox foodCheck = new JCheckBox();
        JButton jButton1 = new JButton();
        JCheckBox voidBought = new JCheckBox();
        JCheckBox voidBought1 = new JCheckBox();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("ArtificialPestControl 1.0");

        jLabel2.setText("Please Choose Boat:");

        jComboBox1.setModel(new DefaultComboBoxModel(new String[]{"Easy Boat", "Medium Boat", "Veteran Boat"}));

        jLabel3.setText("Description: This Script Only Attacks NPC's  in the Middle. for now.");

        portalCheck.setText("Attack Portals");
        portalCheck.setEnabled(false);

        foodCheck.setText("Eat");
        foodCheck.setEnabled(false);

        jButton1.setText("Start ArtificialPestControl");

        jButton1.setText("Start ArtificialPestControl");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        voidBought.setText("Buy Full Void");
        voidBought.setEnabled(false);

        voidBought1.setText("buy Skill");
        voidBought1.setEnabled(false);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(portalCheck)
                                                        .addComponent(foodCheck))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(voidBought1)
                                                        .addComponent(voidBought))))
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(portalCheck)
                                        .addComponent(voidBought))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(foodCheck)
                                        .addComponent(voidBought1))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(ActionEvent evt) {
        if (jComboBox1.getSelectedItem() == "Easy") {
            actionHandler.whichBoat = actionHandler.normalBoat;
            actionHandler.whichPlank = actionHandler.normalJoin;
        } else if (jComboBox1.getSelectedItem() == "Medium") {
            actionHandler.whichBoat = actionHandler.mediumBoat;
            actionHandler.whichPlank = actionHandler.mediumJoin;
        } else if (jComboBox1.getSelectedItem() == "Veteran") {
            actionHandler.whichBoat = actionHandler.veteranBoat;
            actionHandler.whichPlank = actionHandler.veteranJoin;
        }
        actionHandler.runGUI = false;
        dispose();
    }
    // End of variables declaration
}
